export const ActionType = {
  USER_DETAILS: 'USER_DETAILS',
  USER_DEVELOPMENT: 'USER_DEVELOPMENT',
  USER_DEPARTMENT: 'USER_DEPARTMENT',
  USER_INFO_DATA: 'USER_INFO_DATA',
  USER_NAME: 'USER_NAME',
  USER_COMPANY_DATA: 'USER_COMPANY_DATA',
  INCREASE_PROGRESS_BAR: 'INCREASE_PROGRESS_BAR',
}
